### ISSUE TITLE
Ability to append content to start or to end of portal

### ISSUE THREAD

**Issue by piotrpog** [carlcs/craft-twigportal#2]
Right now we can only append content after things that are already added to portal.

**Comment by carlcs** [comment]
I just released beta 2 which adds a `order` param to the `portal` tag. Thanks for the suggestion!
```twig
{% portal 'modals' order 1 %}
    <p>Last Content</p>
{% endportal %}

{% portal 'modals' %}
    <p>Content</p>
{% endportal %}

{% portal 'modals' order -1 %}
    <p>First Content</p>
{% endportal %}
```

**Comment by piotrpog** [comment]
@carlcs Thanks for including it. I will just propose changing the paramater name, because `order -1` is a little awkward. Maybe `append` or `prepend`, without "order" keyword?

I admit that I took this idea from how smarty does it with its blocks.

**Comment by carlcs** [comment]
`order -1` isn’t equivalent to `prepend`. The param as it works right now is that you can set an integer for the position. You can register multiple portals for the same position and they will then be rendered in the target in the same order as they were registered. The default order value is 0.

It’s inspired by https://portal-vue.linusb.org/api/portal.html#order

```twig
{% portal 'modals' order 2 %}
    <p>2nd</p>
{% endportal %}

{% portal 'modals' order 2 %}
    <p>3rd</p>
{% endportal %}

{% portal 'modals' %}
    <p>1st</p>
{% endportal %}
```
