### ISSUE TITLE
Doesn't work when page is cached by Blitz.

### ISSUE THREAD

**Issue by cmalven** [carlcs/craft-twigportal#3]
I noticed on a staging site today that portal content wasn't appearing when the site is cached by [Blitz](https://putyourlightson.com/plugins/blitz). Any idea why that would be the case or how to work around it?

**Comment by carlcs** [comment]
Oops, somehow I have managed to “unwatch” my own repo and didn’t get the notification for this issue.

The issue with Blitz plugin is that it‘s using the same `View::EVENT_AFTER_RENDER_PAGE_TEMPLATE` event that Twig Portal does. This can probably lead to a race condition, which is annoying to debug (I couldn’t reproduce it locally with Blitz caching enabled). But Blitz triggers an event before caching pages, so I have now added my listener to that as well.

I will tag a new release with that added. Please let me know if you’re still having problems with Blitz and Twig Portal.
